apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: owkjegee2-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-45cc604aac.gxpf.p3.openshiftapps.com/rhtap/rhtap-qe:4a0153391f4c93c05074c42a40eaaae4fd122d7b@sha256:623c2a9140abce16b279df7bb7c45585263a433e024bcd127d272f65d450a389
          name: container-image
